### ISSUE TITLE
How to write new values to config file?

### ISSUE THREAD

**Issue by SackCastellon** [uchuhimo/konf#1]
Is there any way to save the changed values to the same file from which the values were loaded, so when the program is run a second time then the new values are loaded?

**Comment by uchuhimo** [comment]
I add support for config export/import in a new release, please check it in v0.7. Now items and associated values in config can be exported to a map, which can be (de)serialized in your favorite format by your favorite serialization library, and be imported into config in the next run. I also provide an example using Java Object Serialization to (de)serialize config (see [config persistence](https://github.com/uchuhimo/konf#config-persistence)). If you need more examples or integrated support (e.g. save/load config to/from YAML/JSON/XML/...), feel free to ask me. Feedback or advice is welcome.

**Comment by SackCastellon** [comment]
It would be great if you could add support to save directly to JSON (for my case), or maybe provide me with an example of how to properly save to JSON because by default the format is not the right one and the workaround I found is not pretty, I would say.

## Example of the problem
### Spec
```kotlin
object server : ConfigSpec("server") {
    val port = optional("port", 3306, "The port of the server")
    val host = required<String>("host", "The host IP of the server")
    val database = required<String>("database", "The name of the database in the server")
}

object login : ConfigSpec("login") {
    val rememberUsername = optional("rememberUsername", false, "Will the last input username be remembered?")
    val username = optional("username", "", "The last input username")
}

val config = Config { addSpec(server);addSpec(login); }.withSourceFrom.json.resource("original.json")
```

### original.json
```json
{
  "server": {
    "host": "example.com",
    "database": "database"
  },
  "login": {
    "rememberUsername": false
  }
}
```

### Code to save JSON
```kotlin
fun main(args: Array<String>) {
    FileWriter("output.json").use {
        GsonBuilder().create().toJson(config.toMap(), it)
    }
}
```

### output.json
```json
{
  "server.port": 3306,
  "server.host": "example.com",
  "server.database": "database",
  "login.rememberUsername": false,
  "login.username": ""
}
```

## Workarround
### original.json
```json
{
  "server": {
    "host": "example.com",
    "database": "database"
  },
  "login": {
    "rememberUsername": false
  }
}
```

### Code to save JSON
```kotlin
fun main(args: Array<String>) {
    val mapToExport = mutableMapOf<String, Any>()

    for (it in config.toTree().items) {

        if (it is OptionalItem)
            if (config[it] == it.default)
                continue

        var map = mapToExport
        it.path.dropLast(1).forEach {
            val tmp: MutableMap<String, Any> =
                    if (map.contains(it)) map[it] as MutableMap<String, Any>
                    else mutableMapOf()
            map.put(it, tmp)
            map = tmp
        }
        map.put(it.path.last(), config[it])
    }

    FileWriter("output.json").use {
        GsonBuilder().create().toJson(mapToExport, it)
    }
}
```

### output.json
```json
{
  "server": {
    "host": "example.com",
    "database": "database"
  }
}
```

**Comment by uchuhimo** [comment]
@SackCastellon I guess you want to merge all updates to config with the original config file and save it as exactly the same format with the original config file. Am I right?

**Comment by uchuhimo** [comment]
@SackCastellon Further question: which of the following ones is your preferred use case:
1. write back all updates to the original config file when exiting
2. write through all updates to the original config file (keep synchronous between config and its source)
3. save all updates to somewhere in certain format for recovering or debugging

**Comment by SackCastellon** [comment]
> @SackCastellon I guess you want to merge all updates to config with the original config file and save it as exactly the same format with the original config file. Am I right?

Yes

> @SackCastellon Further question: which of the following ones is your preferred use case:
>1. write back all updates to the original config file when exiting
>2. write through all updates to the original config file (keep synchronous between config and its source)
>3. save all updates to somewhere in certain format for recovering or debugging

Number 2, as soon as a value is updated write it to the config file

**Comment by SackCastellon** [comment]
@uchuhimo There is a problem with the **kotlinx-bimap** dependency, the **master snapshot of Konf** is looking for version 0.7

![image](https://user-images.githubusercontent.com/5330355/33807186-a8ba8df0-ddca-11e7-92bd-604b9cd4ca1b.png)

But the latest version in your GitHub is [1.0](https://github.com/uchuhimo/kotlinx-bimap#maven)

**Comment by uchuhimo** [comment]
@SackCastellon Sorry for not testing master snapshot from JitPack in advance. It seems like a bug of JitPack , and I have found a workaround for it. Please refresh your dependencies (use `./gradlew build --refresh-dependencies`) and try again.

**Comment by SackCastellon** [comment]
@uchuhimo So far it works well. 👍
If I find any bug I'll let you know

**Comment by uchuhimo** [comment]
I will close this issue. You can open new issue or reopen this issue if any bug is found.

**Comment by uchuhimo** [comment]
The new Writer API has been fully tested. I release it in v0.8 and publish to JCenter.
