### ISSUE TITLE
Please add kotlinx-bimap to published Maven release

### ISSUE THREAD

**Issue by frankie4fingers** [uchuhimo/konf#13]
It's impossible to use Konf out of the box, since it needs additional dependency `kotlinx-bimap` and shows error.
So we forced to include both artifacts to POM:
```
        <dependency>
            <groupId>com.github.uchuhimo</groupId>
            <artifactId>kotlinx-bimap</artifactId>
            <version>v1.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.uchuhimo</groupId>
            <artifactId>konf</artifactId>
            <version>v0.11</version>
        </dependency>
```
It make sense to update repo with new version with full dependencies included or specify this requirement in `readme`.

PS: Thanks for your great work!

**Comment by uchuhimo** [comment]
@frankie4fingers Thank you for your feedback and advise! I have create New Project tickets for Konf (https://issues.sonatype.org/browse/OSSRH-43426) and kotlinx-bimap (https://issues.sonatype.org/browse/OSSRH-43425). I will publish both of them to Maven Central once the tickets are resolved.

**Comment by uchuhimo** [comment]
I have published Konf (https://search.maven.org/artifact/com.uchuhimo/konf/0.12/jar) and kotlinx-bimap (https://search.maven.org/artifact/com.uchuhimo/kotlinx-bimap/1.2/jar) to Maven Central.
