### ISSUE TITLE
Is it possible from an already built map to update all values from that map?

### ISSUE THREAD

**Issue by lamba92** [uchuhimo/konf#16]
Say I have 3 entries in my configuration `A: Int`, `B: String` and `C: Float`. Now I got a map like `[A = 10, B = "ciao"]` and i want to set those values. One way would be to write this file as a JSON and reload from file, is it the only way? It would be perfect something like `conf.loadFromMap(myMap)`. Or maybe `myMap.forEach { k, v -> conf[k] = v }`

**Comment by uchuhimo** [comment]
@lamba92 There is an API to load values from map: `config.from.map.hierarchical(myMap)`. Have a try and tell me whether it fits your need. Thanks!

**Comment by lamba92** [comment]
> @lamba92 There is an API to load values from map: `config.from.map.hierarchical(myMap)`. Have a try and tell me whether it fits your need. Thanks!

Well actually no but I discovered `from.json.string()` which did exactly the job. Is there a way to update the values of an existing config from a source instead of creating a child one?

**Comment by uchuhimo** [comment]
@lamba92 You can use `config.from.json.watchFile("/path/to/file", 100, TimeUnit.MILLISECONDS)` to update the values from a watched file without creating a child one.

**Comment by lamba92** [comment]
I had some time away from work but now I'm back! 
My use case is making REST endpoints for the settings using Ktor. I was considering the `watchFile` but i would have added checks for missing things ecc... 
The solution so far:

```
interface SettingsDefinition {
    var configuration: Config
    val settingsFilePath: Path
}

fun Route.buildRoutesFor(settings: SettingsDefinition) {
    get {
        if (call.request.acceptItems().any { ContentType.Application.Json.match(it.value) })
            call.respondText(ContentType.Application.Json, HttpStatusCode.OK) {
                settings.configuration.toJson.toText()
            }
        else throw IllegalStateException("Header Application/Json missing in get@/api/settings")
    }
    post {
        if (call.request.acceptItems().any { ContentType.Application.Json.match(it.value) }) {
            settings.configuration = settings.configuration.from.json.string(call.receiveText())
            settings.configuration.toJson.toFile(settings.settingsFilePath.toFile())
            call.respond(settings.configuration.toMap())
        } else throw IllegalStateException("Header Application/Json missing in post@/api/settings")
    }
}
```
