### ISSUE TITLE
Case-insensitive resolving of keys

### ISSUE THREAD

**Issue by Cilph** [uchuhimo/konf#18]
I encountered an issue with reading configuration from the environment which made me realize keys are apparently case-sensitive. This is particularly annoying when keys from the environment are all lower-case'd while my ConfigSpec uses camelCase (e.g: DATASOURCECLASSNAME does not map to dataSourceClassName)

Have you considered the ability to resolve keys case-insensitively?

**Comment by uchuhimo** [comment]
@Cilph Thank you for your suggestion! I have release a new version v0.13, in which keys from the system environment are loaded case-insensitively. You can try it now. Any further feedback is welcome.

**Comment by uchuhimo** [comment]
@Cilph The behavior that the function fails when loading the source before using `addSpec` is actually a bug. Konf allows any loading order of source and spec. I have launched a new release v0.13.1 containing the bug fix. v0.13.1 also fixes the problem that the sources jar is empty.
I agree that adopting Spring Boot's relaxed binding rules is useful. I will try to implement this feature, may be included in the next release.
