### ISSUE TITLE
Inconsistent test file/object names

### ISSUE THREAD

**Issue by feature** [uchuhimo/konf#20]
A some of the "spek" tests are suffixed with `Spec` instead of `Spek`.

**Comment by uchuhimo** [comment]
@feature I intend to use `Spec` in all tests to represent "test specification". I have replaced all the tests' `Spek` suffixes to `Spec` in the master branch. Thank you!

**Comment by feature** [comment]
Personally I think `Spek` is a more appropriate suffix, but regardless consistency is more important 👍
