### ISSUE TITLE
Spec#get produces unexpected results

### ISSUE THREAD

**Issue by feature** [uchuhimo/konf#21]
When you try to retrieve a "leaf spec", its `innerSpecs` is not empty. This behavior is unexpected because the spec doesn't have any nested specs declared, and therefore it shouldn't have any `innerSpecs`.

You can run the code below to reproduce the issue:
```kotlin
fun main() {
    check(Service.Backend.Login.innerSpecs.isEmpty()) // innerSpecs is empty as expected
    check(Service["service.backend.login"].innerSpecs.isEmpty())
        { "innerSpecs should be empty because the Login spec doesn't have any nested specs" }
}

// From the example in the README file
object Service : ConfigSpec() {
    object Backend : ConfigSpec() {
        object Login : ConfigSpec() { // Our "leaf spec"
            val user by optional("admin")
        }
    }
}
```

Futhermore looking at the nested tests part of `ConfigSpecTestSpec`, a lot of the results seems unexpected to me, so maybe I'm just not quite understanding the API.

Example:
```kotlin
assertThat(spec["a.bb.inner"].items, isEmpty)
```
This test passes, despite the `Nested.Inner` object having an item named `item` declared.

**Comment by uchuhimo** [comment]
@feature This bug has been fixed in v0.13.2, thank you for your report!
