### ISSUE TITLE
Feature proposal: value validators

### ISSUE THREAD

**Issue by slomkowski** [uchuhimo/konf#27]
It would be nice to have value validation implemented. My idea: `required`, `optional` should have two more lambda arguments, which are both optional:
* add `validIf` parameter to  etc. with following definition: `(value : T) -> Boolean`
* add `invalidValueLazyMessage` with definition: `(value : T) -> String?`

Usage example:

```kotlin
object ExampleConfig : ConfigSpec() {
    val foo by required<Int>(validIf = { it in (0..42) }, invalidValueLazyMessage = { "foo should be between 0 and 42, but is $it" })
}
```
If `validIf` returns *false*, konf throws an exception with optional message evaluated from `invalidValueLazyMessage`.

**Comment by uchuhimo** [comment]
@slomkowski I add a more general notification mechanism to `Item`. Now you can use `Item.onSet` to register callbacks to be invoked when an item is set. You can implement value validator like this:

```kotlin
object ExampleConfig : ConfigSpec() {
    val foo by required<Int>()
    init {
        foo.onSet { value ->
            if (value !in (0..42)) {
                throw RuntimeException("foo should be between 0 and 42, but is $value")
            }
        }
    }
}
```

This feature has been released in v0.13.3, you can give it a try.
