### ISSUE TITLE
Feature: Merge map keys instead of replacing whole map

### ISSUE THREAD

**Issue by pedro-tramontin** [uchuhimo/konf#30]
It would be nice if konf offered the feature to merge map keys instead of replacing whole map from a high precedence configuration file.
Just like spring boot properties work: https://stackoverflow.com/questions/45859131/spring-boot-merging-map-of-map-property

Another example of this:

Suppose I have this two configuration files, with the second file overriding the first one:

**config1.yaml**
```
configuration:
  property_map:
    key1: value1
    key2: value2
```

**config2.yaml**
```
configuration:
  property_map:
    key1: value3
```

And my code looks like this:
```
fun main() {
    var config = Config { addSpec(ConfigurationSpec) }.disable(FAIL_ON_UNKNOWN_PATH)
        .from.yaml.resource("config1.yaml")
        .from.yaml.resource("config2.yaml")

    val propertyMap = config.getOrNull<Map<String, String>>("configuration.property_map")

    println(propertyMap?.get("key1"))
    println(propertyMap?.get("key2"))
}

object ConfigurationSpec : ConfigSpec() {
    val propertyMap by optional(emptyMap<String, String>(), name = "property_map")
}
```

I would like to have the following output from running the above code:
```
value3
value2
```

But instead I get:
```
value3
null
```

Because it replaces the map instead of merging them.

**Comment by uchuhimo** [comment]
@pedro-tramontin Thank you for your advice! This feature is available only when all sources are mergeable. I'm working on migrating all sources to a mergeable tree-based structure. After this renewal, this feature will be easy to support. Since the tree-based source feature is a huge update, there will be some delay before this feature can be released.

**Comment by uchuhimo** [comment]
@pedro-tramontin The requested feature is supported in v0.17.0. You can merge two sources before loading them into the config to merge their keys. The modified version looks like this:

```kotlin
fun main() {
    var config = Config { addSpec(ConfigurationSpec) }.disable(FAIL_ON_UNKNOWN_PATH)
         .withSource(YamlProvider.fromResource("config1.yaml") + YamlProvider.fromResource("config2.yaml"))

    val propertyMap = config.getOrNull<Map<String, String>>("configuration.property_map")

    println(propertyMap?.get("key1"))
    println(propertyMap?.get("key2"))
}

object ConfigurationSpec : ConfigSpec() {
    val propertyMap by optional(emptyMap<String, String>(), name = "property_map")
}
```
