### ISSUE TITLE
Required fields not required?

### ISSUE THREAD

**Issue by emacdona** [uchuhimo/konf#31]
I expect this to throw an exception when executed because I don't have either value defined in my Environment:

```
object DatabaseSpec : ConfigSpec(){
    val connectionString by required<String>()
    val driver by required<String>()
}

val config =    Config{
                    addSpec(DatabaseSpec)
                }
                    .from.env()
```

But it does not throw an exception. Am I misunderstanding what "required" means?

**Comment by emacdona** [comment]
So, after some thought, I can see why env() can't throw b/c we have the ability to chain ".from.json()" and ".from.systemProperties()", etc.

So, could we have a method like "validate()" or "finalize()" or "build()" on Config that would assert that all required properties have been set?

**Comment by opensource21** [comment]
Perhaps `toMap` does this implicit.

**Comment by emacdona** [comment]
Does that work for you? Because I tried that before posting... but it did not work for me. What version of konf are you using?

**Comment by emacdona** [comment]
This, however, did solve my problem:
```fun Config.checkRequired() : Config {
    val missingRequired = filter{ it.isRequired }.map { nameOf( it ) }.toSet().minus(
            toMap().map { (k, _) -> k }
    )
    if(missingRequired.isNotEmpty()){
        throw RuntimeException("Missing Required Properties: \n\t${missingRequired.joinToString(separator = "\n\t")}")
    }
    return this
}```

```val config =    Config {
                    addSpec(SomeSpec)
                }
                .from.json.file("config.json")
                .from.env()
                .checkRequired()```

**Comment by uchuhimo** [comment]
@emacdona I add `config.containsRequired()` (return true/false) and `config.validateRequired()` (throw exception instead) to v0.14.0 to check whether all values of required items exist in config or not. They should meet your requirements.
