### ISSUE TITLE
Hocon substitutions

### ISSUE THREAD

**Issue by GuzelSamigullina** [uchuhimo/konf#32]
Does your `Konf` library support HOCON substitutions (`${foo.bar}`)? It throws me `ConfigException`: `com.typesafe.config.ConfigException$NotResolved: need to Config#resolve()`.

**Comment by carstendev** [comment]
I ran into a similar issue, which seems to happen due to ```Config#resolve()``` not getting called. 

```kotlin
private fun buildConfig(configPath: String): com.uchuhimo.konf.Config {
        val config = com.uchuhimo.konf.Config()
        config.addSpec(ServerSpec)
        config.addSpec(DatabaseSpec)
        config.addSpec(AuthSpec)
        val source = HoconSource(ConfigFactory.parseResources(configPath).resolve().root())
        return config.from.hocon.config.withSource(source)
    }
```
Using the ```ConfigFactory```manually and calling ```resolve```on it fixed the issue for me.

**Comment by uchuhimo** [comment]
@GuzelSamigullina @carstendev I release a new version v0.14.0 which contains this bug fix. You can give it a try.
