### ISSUE TITLE
Config{}.toYaml.toFile(file) doesn't close OutputStream

### ISSUE THREAD

**Issue by Victor9401** [uchuhimo/konf#37]
I am using this library to create temporary configuration files in folders that may be removed by the program or another process later. If I update config and export it to file with `.toYaml.toFile(file)`, the file becomes locked, cause the library doesn't close the OutputStream after the write.

Try running this test (I'm using Apache Commons to delete the file)
```
internal class Test {

    private object TestSpec : ConfigSpec() {
        val testVal by optional("test")
    }

    @Test
    fun testKonfFileAccess() {
        val file = File.createTempFile("test", ".yaml")

        Config { addSpec(TestSpec) }
            .toYaml.toFile(file)

        FileUtils.forceDelete(file)
    }
}
```
You would get an IOException.

As a workaround you can write the file contents with kotlin's writeText:
```
file.writeText(
    Config { addSpec(TestSpec) }
        .toYaml.toText()
)
```
But I belive that's this is not an intended behavior.

**Comment by uchuhimo** [comment]
@Victor9401 Thank you for your bug report. I release a new version v0.15.1, which contains the bug fix. Give it a try.
