### ISSUE TITLE
com.uchuhimo.* dependencies not found from version  0.15 and above

### ISSUE THREAD

**Issue by omarsmak** [uchuhimo/konf#44]
Somehow from version 0.15.x and above, in my gradle project somehow it fails to compile due to missing dependencies of com.uchuhimo.*, e.g:
{code}
> Task :compileKotlin FAILED
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (5, 12): Unresolved reference: uchuhimo
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (6, 12): Unresolved reference: uchuhimo
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (7, 12): Unresolved reference: uchuhimo
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (11, 26): Unresolved reference: Config
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (13, 24): Unresolved reference: ConfigSpec
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (28, 33): Unresolved reference: optional
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (29, 41): Unresolved reference: required
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (30, 37): Unresolved reference: optional
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (31, 39): Unresolved reference: required
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (32, 36): Unresolved reference: optional
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (49, 30): Unresolved reference: Config
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (50, 21): Unresolved reference: addSpec
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (53, 26): Unresolved reference: ConfigException
e: /Users/oalsafi/Private/Projects/kafka-consumer-lag-monitoring/src/main/kotlin/com/omarsmak/kafka/consumer/lag/monitoring/config/KafkaConsumerLagClientConfig.kt: (65, 22): Unresolved reference: ConfigException

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
{code}
This only happens if I update the version to anything from 0.15.x, 0.14.1 works fine. Any hints?

Thanks

**Comment by uchuhimo** [comment]
@omarsmak Thank you for your report! There is a configuration error in `build.gradle.kts` since 0.15. I have fixed it and release a new version v0.21.0. Please have a try and give your feedback if it still fail to compile.

**Comment by omarsmak** [comment]
Awesome! works smoothly. Thanks
