### ISSUE TITLE
[YAML] Path resolution failing if a key is numeric

### ISSUE THREAD

**Issue by dkambersky** [uchuhimo/konf#45]
I apologise if this is intended and documented somewhere, I couldn't find it mentioned anywhere.
Consider this yaml config file:
```
tree:
  1:
    myVal: true
```
This will fail to resolve properly (i.e. `config.at("tree.1.myVal").toValue<Boolean>())`).
However, if that `1` is renamed to `a1`, everything works properly.

**Comment by uchuhimo** [comment]
@dkambersky Thank you for your report! I have fixed it in a new release [v0.22.0](https://github.com/uchuhimo/konf/releases/tag/v0.22.0). Please have a try.

**Comment by dkambersky** [comment]
Thanks for the quick response. It seems like it fails for values over an int's max value - e.g. `484444731619803154`.  The exact error thrown is 

`com.uchuhimo.konf.PathConflictException: "tree.484444731619803154.key" conflicts with existed paths in the tree node`.

**Comment by uchuhimo** [comment]
@dkambersky Yes, it only support int now. You can use `"484444731619803154"` instead of `484444731619803154` to work around it, E.g.,

```yaml
tree:
  "484444731619803154":
    myVal: true
```

Is it necessary to support such a large number in your use case? If not, I will delay `long` / `BigInteger` support to the next release with other features/bugfixes.

**Comment by dkambersky** [comment]
It is really important to me - some of the keys I use are related to
Discord IDs of various elements (ie guilds, users) , which are Longs.
If it would take long to implement I'm not going to keep you from working
on the main update though.
Thanks!

**Comment by uchuhimo** [comment]
@dkambersky I release a new version v0.22.1 that fixes the problem. Please have a try.

**Comment by dkambersky** [comment]
Same error unfortunately :( But I'll just use the string workaround for now, thanks again for being this fast with responding!

**Comment by uchuhimo** [comment]
@dkambersky I have added your example code as tests and all the tests are passed (see https://github.com/uchuhimo/konf/blob/master/konf-yaml/src/test/kotlin/com/uchuhimo/konf/source/yaml/YamlSourceLoadSpec.kt#L44-L73). Thus I believe the error has been gone. Would you like to provide your code that still has the same error?

**Comment by dkambersky** [comment]
I'm sorry, that was my own oversight. It's working fine now. Thanks for the fix!
