### ISSUE TITLE
Support for non map based StdSerializer

### ISSUE THREAD

**Issue by Cybermaxke** [uchuhimo/konf#47]
Given the following custom `StdSerializer`, it's not possible to serialize my custom object as a `String` without getting errors. An json object is expected because it needs to be able to convert to a `Map`. So far it doesn't seem to affect deserialization.

The following example isn't supported: (example error: https://paste.ubuntu.com/p/MhTV9333Qr/)
```kotlin
internal class TextSerializer : StdSerializer<Text>(Text::class.java) {

  override fun serialize(value: Text, gen: JsonGenerator, provider: SerializerProvider) {
    gen.writeString(value.toPlain())
  }
}
```

This works:
```kotlin
internal class TextSerializer : StdSerializer<Text>(Text::class.java) {

  override fun serialize(value: Text, gen: JsonGenerator, provider: SerializerProvider) {
    gen.writeStartObject()
    gen.writeStringField("text", value.toPlain())
    gen.writeEndObject()
  }
}
```

**Comment by uchuhimo** [comment]
@Cybermaxke I have released a new version v0.23.0 that supports non-map based StdSerializer. You can try it now. Any further feedback is welcome.
