### ISSUE TITLE
RFE: optional nullable properties

### ISSUE THREAD

**Issue by DALDEI** [uchuhimo/konf#5]
I would like to have optional nullable config properties.
This is for the case where the property is a class object not a primative so simple defaults dont work well.

Example

```
object BootstrapConfig : ConfigSpec("bootstrap.config")
{
  data class S3Config(val url: String, val region: String ="us-east-1")
  var s3  = required<S3Config>("s3")
  val url =  optional<String>("url","")
  val file = optional<String>("file","")
}
```

I would like s3 to be optional as the above config is intended as a 'union type' -- only 1 of the 3 are needed.  Ideally all 3 should be nullable optional.
I can create a no-arg constructor for S3Config but that is non-ideal as in other cases it may be a fairly large object or testing for 'empty' or 'exists' is non-trivial vs testing for a supplied value with empty fields. 

It appears from the code that it may be nearly as simple as changing the template types to accept <Any?> instead of <Any>

That would allow either optional<S3Config?>("s3",null)  or  required<S3Config>("s3")
I did see the  Item.getOrNull() but not sure how to used that correctly .. I think it was intended for the ase of a named item not existing, not for the value being empty.

Perhaps the UNSET State can be used in some way.
```
if( config[Config.s3].isUnset() ) null else config[Config.s3]    // verbose even if it works 

```

Perhaps another alternative is to make the whole thing 1 class

```
data class S3Config(val url: String, val region: String ="us-east-1")
data class MyConfg( val s3: S3Config? , val url: String? , val file: String?)

object BootstrapConfig : ConfigSpec("bootstrap")
{
  var config  = required<MyConfig>("config")
}
```

I havent tried that yet, not sure if the value prefix's will work in this nested of a config.
e.g. will "bootstrap.config.s3.url" resolve properly to env var "BOOTSTRAP_CONFIG_S3_URL"
or to property "bootstrap.config.s3.url"

Suggestions welcome

**Comment by DALDEI** [comment]
I was able to get this to work somewhat with the following:
```


object BootstrapConfig : ConfigSpec("bootstrap.config")
{
  data class S3Config(val url: String, val region: String ="us-east-1")
  var s3  = required<S3Config>("s3")
  val url =  required<String>("url")
  val file = required<String>("file")
}
...
val config=Config { addSpec(MigrateConfig) }
    .withSourceFrom.toml.run {
      if( bootstrap.getOrNull(BootstrapConfig.s3) != null )
        s3(bootstrap[BootstrapConfig.s3].url, bootstrap[BootstrapConfig.s3].region)
      else
      if( bootstrap.getOrNull(BootstrapConfig.url) != null)
        url(bootstrap[BootstrapConfig.url])
      else
        file(bootstrap[BootstrapConfig.file])
  }


```

It was non-obvious how to do this.  
If there was a way to specify get(Item) to be nullable then it would be simpler to use or atleast more obvious.  e.g.
   val  item = required<Type?>("anullabletype")
....
  config[Spec.item] ?: "a default"

**Comment by uchuhimo** [comment]
@DALDEI 

Nullable items have been supported in konf. You can use something like `val item by optional<Int?>(null)` or `val item by required<Int?>()` to define a nullable item. Loading null values from source or exporting null values through writers is also supported, check the samples to figure out how to declare null values in different sources (e.g. [source.json](https://github.com/uchuhimo/konf/blob/master/src/test/resources/source/source.conf)). Please use [master snapshot of Konf](https://github.com/uchuhimo/konf#gradle-master-snapshot) to try these new features. Any feedback is welcome.

Thanks!
