### ISSUE TITLE
Absence of defined variables overrides defined variables?

### ISSUE THREAD

**Issue by peterfigure** [uchuhimo/konf#56]
Hi - trying out `Konf` and seeing this behaviour:

```
object ServicingConfig : ConfigSpec("servicing") {
    val baseURL by required<String>("baseURL")
}
val config = Config {
     addSpec(ServicingConfig)
}.withSource(
     Source.from.hocon.resource("application.conf") +
        Source.from.env()
)
```

with `application.conf`:
```
servicing {
  baseURL = "https://service/api"
}
```

the result is that `config` is empty. However, if I remove `Source.from.env()` it works as expected. My expectation was that I can override variables set in the hocon config with environmental variables (on a per environment basis for example), the absence of an environmental variable won't displace the defined variable in HOCON. Is that an unrealistic expectation?

**Comment by uchuhimo** [comment]
@peterfigure I have released a new version v0.23.0 that fixes this bug. You can try it now. Any further feedback is welcome.
