### ISSUE TITLE
Example is misleading

### ISSUE THREAD

**Issue by DALDEI** [uchuhimo/konf#7]
In com.uchuhimo.konf.example.Config.kt the example is confusing/misleading:

This code:
```
    val basePort by ConfigSpec("server").required<Int>()
    config.lazySet(Server.port) { it[basePort] + 1 }
    config.lazySet("server.port") { it[basePort] + 1 }
    run {
        var port by config.property(Server.port)
        port = 9090
        check(port == 9090)
    }

```
Is not clear what the intent is.  I doesnt use 'basePort' at all.

Here is an example that may be what the intent was 
```

    val baseSpec =  ConfigSpec("server")
    val basePort by baseSpec.required<Int>()
    config.addSpec( baseSpec )
    config.lazySet(Server.port) { it[basePort] + 1 }
    config.lazySet("server.port") { it[basePort] + 1 }
    run {
        config[basePort] = 8000
        val port by config.property(Server.port)
        check( port == 8001 )
    }

```

**Comment by uchuhimo** [comment]
Thank you for reminding me. I provide example codes in README, and want to verify that all the example codes are valid, so I collect all of them under `com.uchuhimo.konf.example` to make sure they pass the complication when I run `./gradlew build`. I will rename this package to avoid misleading. Any better idea?

**Comment by uchuhimo** [comment]
I have renamed "example" to "snippet".
