### ISSUE TITLE
Concurrent access from multiple processes

### ISSUE THREAD

**Issue by sproctor** [uchuhimo/konf#70]
I'm trying to create a configuration system that can be read or modified from multiple processes. It appears this may be possible by locking the files during writes. Can you give me any guidance on this?

My plan was to do something like:

```kotlin
val config = Config { addSpec(SomeSpec) }.from.hocon.watchFile("preferences.conf")
doSomeStuff()
// first, lock file
preferencesFile.inputStream().channel.lock().use {
    // then apply the new update
    updates(config)

    // Then save the changes to preference
    config.toHocon.toFile(preferencesFile)
}
```

Does that look reasonable? If one client is writing the update, and a second client tries, would it apply the its update without reading the update from the first client and so clobber the first update? I think it should be something like:

```kotlin
// first, lock file
preferencesFile.inputStream().channel.lock().use {
    // refresh config from file here, but I have no idea how to do that

    // then apply the new update
    updates(config)

    // Then save the changes to preference
    config.toHocon.toFile(preferencesFile)
}
```

**Comment by uchuhimo** [comment]
@sproctor The semantics of file-locking APIs are platform-dependent (see https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/nio/channels/FileLock.html#pdep). To guarantee that two updaters won't conflict, you can lock both file and config simultaneously:

```kotlin
config.lock {
    updates(config)
    preferencesFile.inputStream().channel.lock().use {
        config.toHocon.toFile(preferencesFile)
    }
}
```

**Comment by sproctor** [comment]
That's a good point. Ok, so I guess this will be my plan. I'm still slightly concerned about this flow:

process A acquires file lock
process B waits for lock
process A updates config
process A saves config to file
process A releases file lock
process B acquires file lock
process B updates original config (without changes from A)
process B saves config to file, overwriting the changes from A
process B releases file lock

The problem here is that after B acquires the lock, it should reload the file that it is watching, but that won't happen because it's already holding a lock on the config, and I don't know how to manually trigger it.

**Comment by uchuhimo** [comment]
Are there any process except A&B that will update the file?
If not, you don't have to watch the file:

```kotlin
val config = Config { addSpec(SomeSpec) }.from.hocon.file("preferences.conf")
doSomeStuff()
// first, lock config
config.lock {
    // then apply the new update
    updates(config)

    // Then save the changes to preference
    config.toHocon.toFile(preferencesFile)
}
```

If there are other updaters, their priority will be lower than A&B. `watchFile` will flush all values loaded previously in the same layer before loading new values. Thus A&B have to update in a new layer to avoid their updates being flushed:

```kotlin
// add a new layer
val config = Config { addSpec(SomeSpec) }.from.hocon.watchFile("preferences.conf").withLayer()
doSomeStuff()
// first, lock config
config.lock {
    updates(config)
    preferencesFile.inputStream().channel.lock().use {
        config.toHocon.toFile(preferencesFile)
    }
}
```

Process B doesn't have to wait for reloading by `watchFile`, it can see the updates from A. You don't need to worry about updates from `watchFile`, because the priority of its updates are lower than A's updates .

process A acquires config lock
process B waits for config lock
process A updates config (updates from A has been in config)
process A saves config to file
process A releases config&file lock
process B acquires config lock
process B updates original config (B can see updates from A here)
process B saves config to file
process B releases config&file lock

B won't see any expired values here.

**Comment by sproctor** [comment]
I think I'm a bit dense. How can A and B see changes from the other if they don't use `watchFile`? They are two different processes and don't share memory.

**Comment by uchuhimo** [comment]
> How can A and B see changes from the other if they don't use `watchFile`? They are two different processes and don't share memory.

Both of them require the same config's lock, which guarantees that one see changes from the other. See "8.2 Execution Order and Consistency" in [Threads and Locks](https://docs.oracle.com/javase/specs/jvms/se6/html/Threads.doc.html):

> The actions performed by the main memory for any one lock are totally ordered; that is, for any two actions performed by the main memory on the same lock, one action precedes the other.

**Comment by sproctor** [comment]
That only applies to threads within the same process, no? My intention is to run two separate processes that share the config, hence the file lock. Yeah, this makes sense if it were two threads within one process.

**Comment by sproctor** [comment]
I think that `watchFile` isn't usable for my usecase. My current solution is to use a `MutableStateFlow<Config>` and watch the config file and reload the config when it changes.

My original usage was from a bad SO answer. Current update method is something like:
```kotlin
val configState = MutableStateFlow(loadConfig)
var watchKey: WatchKey = ...

RandomAccessFile(preferencesFile, "rw").channel.lock().use {
    watchKey.cancel()
    val config = loadConfig()
    val newConfig = applyUpdates(config)
    newConfig.toHocon.toFile(preferencesFile)
    configState.value = newConfig
    watchKey = ...
}
```

I have another thread monitoring the file for changes.
