### ISSUE TITLE
RFE: Load Config into child prefix.  Or reuse ConfigSpec at new prefix

### ISSUE THREAD

**Issue by DALDEI** [uchuhimo/konf#8]
I am trying to accomplish the following:

In one source (or ideally in the same source, but for simplictiy, 1 source )

base.properties:

```
auth.user=username
auth.password=password
```

In another source I would like to reuse 'auth' as a default for other values.

service.properties

```
service1.url=http://myservice
service2.url=http://myservice
service2.auth.user=user1
service2.auth.password=user2
```

In Application

```

data class Auth(
   val user="",
   val password=""
)


object ServiceSpec :  ConfigSpec() { 
       val url by required<String>()
       val auth by required<Auth>()
}
```
I would like to instantiate something like
```

class Service( config: Config ) {
    val url by config.property( ServiceSpec.url )
    val auth by config.property( ServiceSpec.auth )
}
```

Then in 'pseudo code'
```

val authConfig  = Config { addSpec( ? ) }.withSourceFrom.file("base.properties")
val ServiceConfig = Config  { addSpec( ServiceSpec( ? )  } ?? 
val services = Config( ServiceConfig{ ? } ).withSourceFrom("service.properties")

val service1 = Service( ServiceConfig("service1" ).withValuesFrom(services) ?? .withDefaultsFrom( authConfig ) )
val service2 = Service( ServiceConfig("service2") .withValuesFrom(services)  ?? .withDefaultsFrom(authConfig)) 

```

Couple unresolved issues

1) How to reuse a the same type of ConfigSpec at different prefix's ?  ("service1" and "service1" are the same type at different prefix's 
2) How to inject defaults from a unrelated config  -- into different prefix's 

For while I thought the FlatSource( prefix="xxx" ) might work, but it does not.   The prefix's are all absolute.   Unless I am missing something you cannot derive specs from other specs or load sources or values into any but the root prefix.

This is a very similar but orthagonal feature that layers provide.   Layers let you have defaults on the same prefix but different named layers.

Is there currently a way, or is it conceviable to implement something like 
     Config.loadSourceAt("prefix.nested").from.file("file")
and/or 
     ConfigSpec( parent: ConfigSpec , atPrefix: String ) 

Essentially be able to define ConfigSpecs as reusable types that may occur at different places in a config hierarchy,  AND be able to load Sources from the same or different locations into different prefix'ed roots.

**Comment by DALDEI** [comment]
Some ways this concept may be implemented:

* add an optional prefix to  Config.addSpec() so you can do    Config { addSpec( spec , atRoot="prefix.subprefix" ) }

This could essentially clone spec much like Config layers, by createing a child spec at a new (sub) prefix.

* Child specs -   ConfigSpec.atPrefix( "subprefix").   Takes a ConfigSpec("prefix1") and produces a clone  ConfigSpec("prefix1.subprefix")

* withSource/withValues .at("prefix") ->  load values from source by prepending a prefix to all entries.

**Comment by uchuhimo** [comment]
Thank you for your suggestions. It is a useful feature to make the prefix reconfigurable. Please let me spend some time to consider an appropriate way to support it.
There is a workaround to "change" prefix for source. If you want to change the prefix of a source from `prefix1` to `prefix2`, you can use `mapOf("prefix2" to source["prefix1"]).asSource()` to achieve it (I haven't tested it, but it should work). Furthermore, if you want to change the prefix of a source from `prefix1.sub1` to `prefix2.sub2`, you can use `mapOf("prefix2" to mapOf("sub2" to source["prefix1.sub1"])).asSource()`.
Changing prefix for items in Config and ConfigSpec is impossible, at least for now.

**Comment by DALDEI** [comment]
Thanks.  The specific suggestions are just ideas about how to achieve a larger goal..  For example I currently have a rather crude but effective set of configuration strategies that work well with these concepts.

The basic idea I am attempting to emulate is a first-stab at a property config I am currently using that works well for highly replicated and nested configurations, in my case its largely AWS Resources composed into complex aggregates used by many applications, and then segmented by environment (dev,uat ,prod etc) -- often 5+ levels deep or more.   In the code its undesirable and complex to have to specify the full path mapping to each property as there are many shared classes that occur in many paths.
So instead the 'prefix' is relative to the parent object.  This lets me 'cut off' sub-trees from a larger configuration as well as merge files that configure environment separately from application.
Essentially the path prefixes are determined at the point the source is loaded not at the point the configuration  class structure is defined.   
In general there is also inheritance by path prefix.   E.g.  
```
// auth.user , auth.password , region, name 
class S3Config( val auth: AuthConfig , val region: String , val name: String )
// s3.auth.user, s3.auth.password , s3.region , region  
class Mailer( val s3: S3Config , val region: String )
// inbound.s3.auth... outbound.s3.auth ...
class App( val inbound: Mailer, val outbound: Mailer) 
```
...

Then when loading the configs one can be explicit like
`dev.app1.inbound.s3.auth.password=xxxx
`
or inherited 
```
prod.user=joe
prod.region=us-west-1

```
I implement this by creating a parallel set of defaults based on common path prefixes 
*in addition to* defaults based on source 'layer'. 
Each sub-config is addressable by the full path from 'root', as well as relative paths to each of its parents.
e.g when resolving   auth.password  it looks for  "password" , "auth.password" , <parent>."auth.password", .... and stopping after the top most path is checked allowing the most specific (longest) path specification to take precedence.

This technique was very common in property files for X  Windows long long ago ...  where one could set say a global 'background.color=blue' but a app specific  'xterm.menu.file.open.background.color=red'
This type of defaults by specificity overlays the defaults by source or layer -- so one can specify env vars, command line, files etc as you do with konf current to give a priority by source location, but then also have a priority by specificity independent of that. 
CSS does something similar to this but vastly more complex.


--- 
As a tangent -- I have a 'philosophical goal' that it should be possible to not have to replicate the definition of the specification object and the class object that holds the values (if there is one).
This is a difficult problem -- and you have made great steps -- 
But 'in theory'  one shoujld be able to define a single class/interface/DSL/whatever that is sufficient for the specification AND the values without having to replicate all the names and types.
The recent change to using 'by' instead of '=' is close ... imagine

class MyConf(config: Config)  { 
    val port by config<Int>(10)  // or
    val port : Int by config(description="A port",default=10 )  
}
something like that *should be sufficient* to both specify the 'Items' as well as use in place by 
code not expecting anything but a simple property 

mailer( val MyConf: conf ) {  fun openConnection = open( conf.port )  }

Without resorting to annotations or code injection or pre-processing.
Thats my 'theory' -- :)

**Comment by uchuhimo** [comment]
@DALDEI 

Prefix operations for Source/Config/ConfigSpec are fully supported now. you can:
- drill down using `source["a.b"]` or `config.at("a.b")` or `spec["a.b"]`
- roll up using `source.withPrefix("a.b")` or `config.withPrefix("a.b")` or `spec.withPrefix("a.b")`
    - DSL for `withPrefix` operation: `Prefix("a.b") + source` or `Prefix("a.b") + config` or `Prefix("a.b") + spec`

Ad-hoc config item is also supported. Here is an example:

```kotlin
class AdHocNetworkBuffer(config: Config) {
    private val root = config.at("network.buffer")

    val size by root.required<Int>(description = "size of buffer in KB")

    val maxSize by root.lazy(name = "max-size", description = "max size of buffer in KB") { size * 2 }

    val name by root.optional("buffer", description = "name of buffer")

    val type by root.optional(
        Type.OFF_HEAP,
        prefix = "heap",
        description = """
            | type of network buffer.
            | two type:
            | - on-heap
            | - off-heap
            | buffer is off-heap by default.
            """.trimMargin("| "))

    enum class Type {
        ON_HEAP, OFF_HEAP
    }
}
```

Please use [master snapshot of Konf](https://github.com/uchuhimo/konf#gradle-master-snapshot) to try these new features, and tell me:
- Do these features cover your use cases?
- Any bug you find (since I have no time to fully test them this weekend)

Thanks!

**Comment by uchuhimo** [comment]
Now you can cast config to a specified class, konf will inject value into fields in the class for you. See [AdHocConfigItemSpek.kt#L45](https://github.com/uchuhimo/konf/blob/master/src/test/kotlin/com/uchuhimo/konf/AdHocConfigItemSpek.kt#L45) for more details.

**Comment by DALDEI** [comment]
I dont quite see what is happening in this code.  I will write back after I study it more.
